refactoring Organization classes
munHunger/Hackademy-IV-backend pull request #5
Opened 2017-10-17 14:42 UTC by najlaalhaj

2017-10-17 15:12 UTC, najlaalhaj commented
Refactoring OrganizationAPI,OrganizationService,Organization and Database classes

2017-10-17 16:48 UTC, munHunger requested changes

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +// end point for all Organization operations
Change to use javadoc comment style, i.e.
/**
  * documentation
  */

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +
use javadoc style. se other comment

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +    //a method to update an organization object that already saved in the database
use javadoc style. se other comment

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +    //a method to retrieve an organization object from the database based on the organizationID
use javadoc style. se other comment

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +        return new io.orten.nano.impl.OrganizationService().getAll();
remove full package name as it is not needed here

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +    @Consumes
This annotation is not doing anything

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +        return new io.orten.nano.impl.OrganizationService().delete(orgID);
Remove full package name

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/business/OrganizationAPI.java
> +    @Produces(MediaType.TEXT_PLAIN)
Why are you suddenly producing TEXT_PLAIN?

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +            return Response.status(HttpServletResponse.SC_NOT_FOUND).entity(e.getMessage()).build();
This is bad practice.
What would happen if for example the database is unavailable?
I would recomend checking if the database returns null, and if so, then return 404.

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +            return Response.status(HttpServletResponse.SC_NO_CONTENT).entity(e.getMessage()).build();
Same as for get.
In 90% of all cases you should only return a 500 server error if you catch an exception

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +            return Response.status(HttpServletResponse.SC_NOT_FOUND).entity(e.getMessage()).build();
Same as for get

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +            return Response.status(HttpServletResponse.SC_GONE).entity(Database.deleteOrganization(orgID)).build();
SC_GONE is an error code and thus shouldn't be returned if everything went as expected

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +
Remove empty lines

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/model/Organization.java
> +  represents an organization raising fund for one or more projects
use javadoc code style

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/model/Organization.java
> + /**
fix indentation

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +//  Creates and manages connections with and transactions to the database
use javadoc code style

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +    public static List<Organization> getOrganization(String orgID) {
It is quite wierd to return a list of one Organization.
You should probably return the first one if one exists(or null).

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +    public static String deleteOrganization(String orgID){
Why return a String from the delete?
Could probably return a boolean for if something to delete was found or not

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +            s.beginTransaction();
You don't need to begin(or commit) a transaction if you are just retrieving data

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +            s.beginTransaction();
You don't need to begin(or commit) a transaction if you are just retrieving data

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +    public static Session getSession() throws Exception {
Is this used?

2017-10-17 16:48 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +
Remove empty lines

2017-10-22 09:13 UTC, munHunger requested changes

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/impl/OrganizationService.java
> +
lot of empty lines here

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/impl/ProjectService.java
> +            if (fundedProjects.size()!=0){
Could be replaced with fundedProjects.isEmpty()

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +            s.update(org);
shouldn't you also commit the transaction?

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +                s.beginTransaction().commit();
begin a transaction and the commit it right away?
that seems odd

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +            s.beginTransaction();
Why begin a transaction if you are not going to commit it?
in this case you don't need to begin a transaction

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +            s.beginTransaction();
Why begin a transaction if you are not going to commit it?
in this case you don't need to begin a transaction

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +
empty lines that could be removed

2017-10-22 09:13 UTC, munHunger commented on src/main/java/io/orten/nano/util/Database.java
> +
empty lines that could be removed

2017-10-22 09:31 UTC, munHunger approved these changes

2017-10-22 09:35 UTC, najlaalhaj commented
finally approved!

2017-10-22 09:46 UTC, merged